services:
  blog-fe:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "81:81"
    volumes:
      - .:/var/www
    networks:
      - sail
networks:
    sail:
        driver: bridge
        external: true

       